version: "3"

services:
  backend:
    container_name: arkham-collection_backend
    build: backend
    stdin_open: true
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app

  frontend:
    container_name: arkham-collection_frontend
    build: frontend
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  deck-builder:
    container_name: arkham-collection_deck-builder
    build: deck-builder
    stdin_open: true
    ports:
      - 3001:3001
      - 3010:3010
    volumes:
      - ./deck-builder:/app

  postgres:
    container_name: arkham-collection_postgres
    image: postgres:13-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=""
      - POSTGRES_DB=bouwdata
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
